controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
explorer:
    path: /explorer
    controller: App\Controller\ExplorerController::index


